### ISSUE TITLE
setCameraParams出错

### ISSUE THREAD

**Issue by mishaoshuai** [Gentleman-jun/VideoRecordDemo#1]
11-15 11:06:39.056: E/AndroidRuntime(27839): java.lang.RuntimeException: setParameters failed
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at android.hardware.Camera.native_setParameters(Native Method)
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at android.hardware.Camera.setParameters(Camera.java:1614)
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at com.liuzhongjun.videorecorddemo.activity.CustomRecordActivity.setCameraParams(CustomRecordActivity.java:204)
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at com.liuzhongjun.videorecorddemo.activity.CustomRecordActivity.initCamera(CustomRecordActivity.java:170)
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at com.liuzhongjun.videorecorddemo.activity.CustomRecordActivity.access$0(CustomRecordActivity.java:157)
11-15 11:06:39.056: E/AndroidRuntime(27839): 	at com.liuzhongjun.videorecorddemo.activity.CustomRecordActivity$2.surfaceCreated(CustomRecordActivity.java:133)

**Comment by Gentleman-jun** [comment]
这个是底层抛出的错误，你看一看是否是机型适配的原因

**Comment by magiclonw** [comment]
params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO); 这句注了就行了

**Comment by mishaoshuai** [comment]
谢谢，我有时间试试

**Comment by magiclonw** [comment]
params.setFocusMode(params.getFocusMode()); 要么改成这样的

**Comment by mishaoshuai** [comment]
好的，谢谢大佬
